### ISSUE TITLE
Missile Production

### ISSUE THREAD

**Issue by Darcman99** [Darcman99/Sarcina#10]
Invisible jobs which on landing gives the player missile ammunition.
Requires harvested metals to give ammunition.
Requires a special outfit or set of outfits to process the harvested metals.

**Missiles**
- [ ] Finisher Torpedo
- [ ] Korath Mine
- [ ] Korath Piercer

**Comment by KiLEdEnNis** [comment]
~I smell a stolen idea~
*remembers his own Nekris Predator sprite*
actually, nvm
