### ISSUE TITLE
Clean Up Assets

### ISSUE THREAD

**Issue by Darcman99** [Darcman99/Sarcina#17]
Clean up as in run through all of the blends used in this plugin, minimising on objects and materials.
Any objects that are symmetrical in appearance will be joined and mirrored to ensure 100% symmetry and cut down on objects used.

- [x] Outfits
- [x] Ships

**Comment by KiLEdEnNis** [comment]
finally someone else that'll have remotely clean Blends
I don't accept anything below my own quality of cleanliness
