### ISSUE TITLE
The Irm

### ISSUE THREAD

**Issue by Darcman99** [Darcman99/Sarcina#2]
Single star system species north of Waypoint.
Accessible via a second wormhole in Waypoint.
Wormhole only accessible with a special outfit (e.g. Keystone) which is only available in that single star system.
Only ships will be carriers and drones.
Carriers have in-built cloaking ability, drones do not.
Cloak will require an immense amount of power to maintain.
Engines will be extremely efficient, as in average thrust and turn but less energy consumption and even less heat generation.
Ships will get in-built solar generation and absurd energy capacity.
Spinal Beam (Devastator) is hard hitting, will do mainly heat damage.
Custom projectile needed, currently using resized Korath Fire-Lance projectile.
Carrier will be named Apocalypse, drone will be named Locust.

**Apocalypse**
- [x] Sprite
- [x] Stats
- [x] Implementation

**Devastator**
- [x] Projectile
- [x] Effects
- [x] Stats
- [x] Implementation

**Irm Large Engines**
- [x] Flare
- [x] Stats
- [x] Implementation

**Irm Small Engines**
- [x] Flare
- [x] Stats
- [x] Implementation

**Reflective Plating**
- [x] Stats
- [x] Implementation

**Revelation**
- [ ] Sprite
- [x] Stats
- [x] Implementation

**Comment by KiLEdEnNis** [comment]
expect my Apocalypse cleanup within 2 Wanderer solar cycles
